steps:
- name: prepare-runtime
  args: ['bash', '-c', '"sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n -t ."']
artifacts:
  objects:
    location: 'gs://activestate_test_artifacts/'
    paths: ['state-tool']