steps:
- name: docker.io/activestate/state_gcb
  args: ['which', 'state']
- name: docker.io/activestate/state_gcb
  args: ['bash', '-c', '"/usr/local/bin/state run prepare"']
- name: docker.io/activestate/state_gcb
  args: ['cat', '/workspace/.cfg/config.yaml']
- name: docker.io/activestate/state_gcb
  args: ['state', 'run', 'recipe']
  env:
    - 'VERBOSE=true'
- name: docker.io/activestate/state_gcb
  args: ['state', 'auth']
artifacts:
  objects:
    location: 'gs://activestate_test_artifacts/'
    paths: ['output']
options:
  env:
  - 'ACTIVESTATE_CLI_DISABLE_UPDATES=true'
  - 'ACTIVESTATE_CLI_CONFIGDIR=/workspace/.cfg'
  - 'ACTIVESTATE_CLI_CACHEDIR=/workspace/.cache'