steps:
- name: gcr.io/cloud-builders/gcloud
  args: ['beta', '--help']
- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'secrets', 'versions', 'access', '1', '--secret=ACTIVESTATE_API_KEY']
- name: docker.io/activestate/state_gcb
  args: ['state', 'run', 'prepare']
- name: docker.io/activestate/state_gcb
  args: ['state', 'run', 'recipe']
- name: docker.io/activestate/state_gcb
  args: ['state', 'auth']
artifacts:
  objects:
    location: 'gs://activestate_test_artifacts/'
    paths: ['output']
options:
  env:
  - 'ACTIVESTATE_CLI_DISABLE_UPDATES=true'
  - 'ACTIVESTATE_CLI_CONFIGDIR=/workdir/.cfg'
  - 'ACTIVESTATE_CLI_CACHEDIR=/workdir/.cache'