steps:
- name: docker.io/activestate/state_gcb
  env:
  - 'ACTIVESTATE_CLI_DISABLE_UPDATES=true'
  args: ['state', 'run', 'recipe']
- name: docker.io/activestate/state_gcb
  args: ['cat', 'output']
artifacts:
  objects:
    location: 'gs://activestate_test_artifacts/'
    paths: ['out']