steps:
- name: docker.io/activestate/state_gcb
  args: ['state', 'run', 'recipe']
- name: docker.io/activestate/state_gcb
  args: ['cat', 'out']
artifacts:
  objects:
    location: 'gs://activestate_test_artifacts/'
    paths: ['out']