steps:
- name: docker.io/activestate/state_gcb
  args: ['state', 'deploy', 'ActiveState/cli', '--path', '/workspace/.state']
- name: docker.io/activestate/state_gcb
  args: ['python3', '--version']
- name: docker.io/activestate/state_gcb
  args: ['state', 'auth']
artifacts:
  objects:
    location: 'gs://activestate_test_artifacts/'
    paths: ['output']
options:
  env:
  - 'ACTIVESTATE_CLI_DISABLE_UPDATES=true'
